### ISSUE TITLE
[Feature Request] Output Directory Settings

### ISSUE THREAD

**Issue by Sytronik** [ashthespy/Atom-LaTeX#196]
Hi, 
Can you make a setting item for output directory?
Of course I could use `pdflatex -output-directory=` option or `latexmk -outdir=` option,
however in that case, atom-latex cannot open the output pdf file.
It seems atom-latex assumes the output file is in the same directory as the root TeX file.

I think this feature is beneficial for many people.
Thanks.

**Comment by tillyboy** [comment]
+1, I just debugged automatic opening. Had to put `latexmk && mv build/main.pdf ./` as custom toolchain. That is however restricted to the specific setup and not portable across projects.
While the best solution would clearly be to set the output directory within this package, maybe someone here knows if there is a way to add a post-build hook to `latexmkrc`.
That way we could at least have a perl function handle this instead of changing the toolchain for every project.
